# Site settings
title: "Resume"
description: "A resume to express me"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "이재연"
resume_title:                   "Backend · Frontend · iOS Developer"
resume_contact_email:           "leejaeduss@gmail.com"
resume_header_intro: "23&nbsp;&nbsp;·&nbsp;&nbsp;1995.04.17&nbsp;&nbsp;·&nbsp;&nbsp;leejaeduss@gmail.com"
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
resume_social_links:
  resume_github_url:            "https://github.com/leejaedus"
  resume_linkedin_url:          "https://www.linkedin.com/in/%EC%9E%AC%EC%97%B0-%EC%9D%B4-987b00126/"
  resume_website_url:           "http://blog.flative.io/authors/%EC%9D%B4%EC%9E%AC%EC%97%B0/"
resume_print_social_links:      true
resume_theme:                   default
