# Site settings
title: "Resume"
description: "A resume to express me"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "이재연"
resume_title:                   "Software Engineer"
resume_contact_email:           "leejaeduss@gmail.com"
#resume_header_message: "2019. 09. 02. 까지 산업 기능 요원"
#resume_header_intro: "1995.04.17.&nbsp;&nbsp;·&nbsp;&nbsp;leejaeduss@gmail.com&nbsp;&nbsp;·&nbsp;&nbsp;중앙대학교 기계공학부 2학년"
#resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
resume_social_links:
  resume_github_url:            "https://github.com/leejaedus"
  resume_linkedin_url:          "https://www.linkedin.com/in/%EC%9E%AC%EC%97%B0-%EC%9D%B4-987b00126/"
#  resume_website_url:           "https://flative.github.io/blog/authors/%EC%9D%B4%EC%9E%AC%EC%97%B0/"
resume_print_social_links:      true
resume_theme:                   default
